### ISSUE TITLE
Traceback when running run.py

### ISSUE THREAD

**Issue by mLgz0rn** [tam1m/jellybean#1]
Hello!

I just stumbled upon this project by accident and wanted to test it out.
When running the run.py I get the following traceback

```
2023-06-29 20:05:49,764 - INFO - Lodaded config.yaml:
 {'Film 4K': {'enabled': True, 'overlays': True}, 'Serier 4K': {'enabled': True, 'overlays': True}}
Traceback (most recent call last):
  File "/home/mikkel/jellybean/run.py", line 513, in <module>
    main()
  File "/home/mikkel/jellybean/run.py", line 100, in main
    libraries_dict.update({library: {"parent_id": parent_id, "collection_type": collection_type}})
                           ^^^^^^^
UnboundLocalError: cannot access local variable 'parent_id' where it is not associated with a value
```

**Comment by mLgz0rn** [comment]
I think I figured out the problem.

It just looks for the first user that is an admin, but if that admin does not have access to the libraries it will not work.
I have a user I use for invites only and it requires admin but does not require access to libraries, and that user is the first one that is admin.
Quick fix for me is to give that user access to the libraries, but I think the real fix should also be to check is the user is admin and has access to the required libraries!
